const ADD_TO_CART = "ADD_TO_CART"
const REMOVE_ITEM ="REMOVE_ITEM"
const TOTAL_ITEMS = "TOTAL_ITEMS"
const SET_INCREMENT = "SET_INCREMENT"
const SET_DECREMENT= "SET_DECREMENT"
export {ADD_TO_CART, REMOVE_ITEM, TOTAL_ITEMS, SET_INCREMENT, SET_DECREMENT}