const ADD_TAG = "ADD_TAG";
const REMOVE_TAG = "REMOVE_TAG";
const SORT_BY = "SORT_BY";
const ADD_FOOD_PREFERENCE = "ADD_FOOD_PREFERENCE";
const REMOVE_FOOD_PREFERENCE = "REMOVE_FOOD_PREFERENCE";
const START_PRICE = "START_PRICE";
const END_PRICE = "END_PRICE";
const ADD_RATING = "ADD_RATING";
const REMOVE_RATING = "REMOVE_RATING";
const ADD_DISCOUNT = "ADD_DISCOUNT";
const REMOVE_DISCOUNT = "REMOVE_DISCOUNT";
const ADD_PACKSIZE = "ADD_PACKSIZE";
const REMOVE_PACKSIZE = "REMOVE_PACKSIZE";
const SET_PAGES = "SET_PAGES";

const KEY_SEARCH = "KEY_SEARCH";

export {
  ADD_TAG,
  REMOVE_TAG,
  SORT_BY,
  ADD_FOOD_PREFERENCE,
  REMOVE_FOOD_PREFERENCE,
  START_PRICE,
  END_PRICE,
  ADD_RATING,
  REMOVE_RATING,
  ADD_DISCOUNT,
  REMOVE_DISCOUNT,
  ADD_PACKSIZE,
  REMOVE_PACKSIZE,
  SET_PAGES,
  KEY_SEARCH
};
